name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run JavaScript tests
        run: npm test

      - name: Run CSS linting
        run: npx stylelint "**/*.css"
